<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_dome/src/domeuser.proto

namespace Domefoo;

/**
 * <pre>
 *类注释:用户类型
 * </pre>
 *
 * Protobuf enum <code>domefoo.UserDomeType</code>
 */
class UserDomeType
{
    /**
     * <pre>
     *类型1
     * </pre>
     *
     * <code>BASE = 0;</code>
     */
    const BASE = 0;
    /**
     * <pre>
     *类型2
     * </pre>
     *
     * <code>HIG = 1;</code>
     */
    const HIG = 1;
    /**
     * <pre>
     *类型3
     * </pre>
     *
     * <code>LOW = 2;</code>
     */
    const LOW = 2;
}

